defaultSourceData: "file"           # for import of data
defaultSourceModel: "file"           # for import of models
fileExtension: "plotr"      # for download of models
rPackageName: "PlotR"       # for download and import of models
